# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='ProtectedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pdf', 'PDF File'), ('gallery', 'Gallery')], max_length=7)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('page_name', models.CharField(max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
            ],
            options={
                'verbose_name': 'Image gallery',
                'proxy': True,
                'verbose_name_plural': 'Image galleries',
                'indexes': [],
            },
            bases=('protected_pages.protectedpage',),
        ),
        migrations.CreateModel(
            name='PDFpage',
            fields=[
            ],
            options={
                'verbose_name': 'PDF page',
                'proxy': True,
                'verbose_name_plural': 'PDF pages',
                'indexes': [],
            },
            bases=('protected_pages.protectedpage',),
        ),
        migrations.AddField(
            model_name='image',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protected_pages.ImageGallery'),
        ),
    ]
