# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20171212_0235'),
        ('protected_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protectedpage',
            name='parent_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Page'),
        ),
    ]
