# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protected_pages', '0002_protectedpage_parent_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protectedpage',
            old_name='page_name',
            new_name='heading',
        ),
        migrations.AddField(
            model_name='protectedpage',
            name='paragraph',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='protectedpage',
            name='subheading',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
