# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 19:25
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('protected_pages', '0004_auto_20180107_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectedpage',
            name='paragraph',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
