# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protected_pages', '0006_auto_20180107_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('image',)},
        ),
    ]
