# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protected_pages', '0008_auto_20180107_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'ordering': ('order',), 'verbose_name': 'Image gallery', 'verbose_name_plural': 'Image galleries'},
        ),
        migrations.AlterModelOptions(
            name='pdfpage',
            options={'ordering': ('order',), 'verbose_name': 'PDF page', 'verbose_name_plural': 'PDF pages'},
        ),
    ]
