# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_globals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globals',
            name='page_background_color',
            field=models.CharField(default='rgba(89,89,89,0.1)', max_length=500, null=True),
        ),
    ]
