# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('page_name', models.CharField(max_length=500, null=True)),
                ('lrg_columns', models.IntegerField(blank=True, null=True)),
                ('md_columns', models.IntegerField(blank=True, null=True)),
                ('sm_columns', models.IntegerField(blank=True, null=True)),
                ('copy', tinymce.models.HTMLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
