# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20171110_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='text_format',
            field=models.CharField(blank=True, default='text-justify', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='num_columns',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
    ]
