# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20171124_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='ProtectedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pdf', 'PDF File'), ('gallery', 'Gallery')], max_length=1)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('page_name', models.CharField(max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=b'')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Image')),
            ],
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('pages.protectedpage',),
        ),
        migrations.CreateModel(
            name='PDFpage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('pages.protectedpage',),
        ),
    ]
