# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_image_imagegallery_pdfpage_protectedpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protectedpage',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.ImageGallery'),
        ),
    ]
