# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20171212_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectedpage',
            name='type',
            field=models.CharField(choices=[('pdf', 'PDF File'), ('gallery', 'Gallery')], max_length=7),
        ),
    ]
