# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20171212_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='ImageGallery',
        ),
        migrations.DeleteModel(
            name='PDFpage',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ProtectedPage',
        ),
    ]
